var ADDRESS_KNOWN = {
"rvYAfWj5gh67oV6fW32ZzP3Aw4Eubs59B" :"Bitstamp",
"rrpNnNLKrartuEqfJGpqyDwPj1AFPg9vn1":"Bitstamp hotwallet",
"rLEsXccBGNR3UPuPu2hUXPjziKC3qKSBun":"RockTrading",
"rPDXxSZcuVL3ZWoyU82bcde3zwvmShkRyF":"WirePass",
"r9xAQUyqs53QH2PLxe7iFbNbpU2RA9QtZx":"WirePass hotwallet",
"rMwjYedjc7qqtKYVLiAccJSmCwih4LnE2q":"SnapSwap",
"rhasPLL5GaXzBh5amQkN7Dr1SNF4Whb2ZT":"SnapSwap hotwallet",
"r3ADD8kXSUKHd6zTCKfnKT3zV9EZHjzp1S":"RippleUnion",
"rNPRNzBB92BVpAhhZr4iXDTveCgV5Pofm9":"RippleIsrael",
"rfYv1TXnwgDDK4WQNbFALykYuEBnrR4pDX":"DividendRippler",
"rnuF96W4SZoCJmbHYBFoJZpR8eCaxNvekK":"RippleCN",
"rno91tGDJeRcnM7EMXj8KG9UTyxRGMMz8s":"RippleCN hotwallet",
"rNaptDNfFXo1quhKwMaNPf66iwPqA8YLky":"RippleCN hotwallet2",
"rfNNhNeeuXj6vgY31pVu3Ge2DuEDEtgSor":"RippleCN withdrawl",
"rEKbakXJMo4Cnb7WJekVW38mANAMXajAXi":"RippleTo",
"razqQKzJRdB4UxFPWf5NEpEG3WMkmwgcXA":"RippleChina",
"r45dBj4S3VvMMYXxr9vHX4Z4Ma6ifPMCkK":"RippleChina hotwallet",
"rGYYWKxT1XgNipUJouCq4cKiyAdq8xBoE9":"Rippay",
"rKiCet8SdvWxPXnAgYarFUXMh1zCPz432Y":"RippleFox",
"r9Dr5xwkeLegBeXq6ujinjSBLQzQ1zQGjH":"RippleSingapore",
"rsYnSWfvcJPpKC1QwDfdLixdk8VNQpAUv5":"HotXRP",
"rM8199qFwspxiWNZRChZdZbGN5WrCepVP1":"XRPChina",
"rE7CNMbxwvTQrqSEjbcXCrqeN6EZga1ApU":"RippleFund",
"rMAz5ZnK73nyNUL4foAvaxdreczCkG3vA6":"RippleTradeJapan",
"r9vbV3EHvXWjSkeQ6CAcYVPGeq7TuiXY2X":"WeExchange USD",
"rBcYpuDT1aXNo4jnqczWJTytKGdBGufsre":"WeExchange AUD",
"rpvfJ4mR6QQAeogpXEKnuyGBx8mYCSnYZi":"WeExchange BTC",
"r47RkFi1Ew3LvCNKT6ufw3ZCyj5AJiLHi9":"WeExchange CAD",
"rsP3mgGb2tcYUrxiLFiHJiQXhsziegtwBc":"Coinex",
"ra9eZxMbJrUcgV8ui7aPc161FgrqWScQxV":"PeerCover",
"rfK9co7ypx6DJVDCpNyPr9yGKLNer5GRif":"PeerCover PCV",
"rJHygWcTLVpSXkowott6kzgZU6viQSVYM1":"Justcoin",
"rPKSvQ1qFAksr7hzk2wC2xtqSqFbxP3wvg":"NoFiatCoin",
"rExAPEZvbkZqYPuNcZ7XEBLENEshsWDQc8":"ripplerm",
"rFLiPGytDEwC5heoqFcFAZoqPPmKBzX1o" :"Rippleflip hotwallet",
"r2hrqyjdLCBSkB6ADLpWkWtYFK96w1xMn" :"ripplegiveaway.com",
"r32xbjHr824To4sYYXhZSqzifhwCbVw4vD":"31sky.net",
"rNKXT1p7jpt5WxSRSzmUV6ZB6kY7jdqHmx":"RL WCG giveaway",
"rMTzGg7nPPEMJthjgEBfiPZGoAM7MEVa1r":"RL Forum giveaway",
"r3kmLJN5D28dHuH8vZNUZpMC43pEHpaocV":"OC initial giveaway",
"r43mpEMKY1cVUX8k6zKXnRhZMEyPU9aHzR":"200M",
"rHWPTbajsPaSJ1FepcgNNx4FjyghukNBfi":"BTC38",
"rMMWFA9TkQ9bpJCadDfCpbHcS79Y7GyP3k":"BTC38 hot"}